x-service: &default-service
  restart: always

x-aggregator-service: &default-aggregator-service
  <<: *default-service
  image: easytrade-aggregatorservice
  depends_on:
    - offerservice

x-aggregator-service-env: &default-aggregator-service-env
  OFFER_SERVICE: offerservice:8080

x-feature-flag-service: &feature-flag-service-env
  FEATURE_FLAG_SERVICE_PROTOCOL: http
  FEATURE_FLAG_SERVICE_BASE_URL: feature-flag-service
  FEATURE_FLAG_SERVICE_PORT: 8080

x-connection-strings:
  JAVA_CONNECTION_STRING: &java-connection-string jdbc:sqlserver://db:1433;database=TradeManagement;user=sa;password=yourStrong(!)Password;encrypt=false;trustServerCertificate=false;loginTimeout=30;
  DOTNET_CONNECTION_STRING: &dotnet-connection-string Data Source=db;Initial Catalog=TradeManagement;Persist Security Info=True;User ID=sa;Password=yourStrong(!)Password;TrustServerCertificate=true
  GO_CONNECTION_STRING: &go-connection-string sqlserver://sa:yourStrong(!)Password@db:1433?database=TradeManagement&connection+encrypt=false&connection+TrustServerCertificate=false&connection+loginTimeout=30

networks:
  mynetwork:
    external: true

services:
  db:
    <<: *default-service
    build: src/db
    image: db:${BUILD_NUMBER}
    container_name: default-service
    ports:
      - 1433:1433
    networks:
      - mynetwork      
    environment:
      SA_PASSWORD: yourStrong(!)Password
      DT_CLUSTER_ID: easytrade-default-service-${STAGE}
      JOB_NAME: ${JOB_NAME}
      RELEASE_VERSION: ${BUILD_NUMBER}
      RELEASE_STAGE: ${STAGE}
      DT_TAGS: Environment=${STAGE} Service=default-service 
      DT_CUSTOM_PROP: ENVIRONMENT=${STAGE} JOB_NAME=${JOB_NAME} BUILD_NUMBER=${BUILD_NUMBER}
      

  contentcreator:
    <<: *default-service
    build: src/contentcreator
    image: contentcreator:${BUILD_NUMBER}
    container_name: contentcreator 
    depends_on:
      - db
    networks:
      - mynetwork      
    environment:
      MSSQL_CONNECTIONSTRING: *java-connection-string
      DT_CLUSTER_ID: easytrade-contentcreator${STAGE} 
      JOB_NAME: ${JOB_NAME}
      RELEASE_VERSION: ${BUILD_NUMBER}
      RELEASE_STAGE: ${STAGE}
      DT_TAGS: Environment=${STAGE} Service=contentcreator 
      DT_CUSTOM_PROP: ENVIRONMENT=${STAGE} JOB_NAME=${JOB_NAME} BUILD_NUMBER=${BUILD_NUMBER}

  manager:
    <<: *default-service
    build: src/manager/easyTradeManager
    image: manager:${BUILD_NUMBER}
    container_name: manager 
    depends_on:
      - db
    networks:
      - mynetwork      
    ports:
      - 8081:80
    environment:
      MSSQL_CONNECTIONSTRING: *dotnet-connection-string
      PROXY_PREFIX: manager
      DT_CLUSTER_ID: easytrade-manager${STAGE} 
      JOB_NAME: ${JOB_NAME}
      RELEASE_VERSION: ${BUILD_NUMBER}
      RELEASE_STAGE: ${STAGE}
      DT_TAGS: Environment=${STAGE} Service=manager 
      DT_CUSTOM_PROP: ENVIRONMENT=${STAGE} JOB_NAME=${JOB_NAME} BUILD_NUMBER=${BUILD_NUMBER}

  pricing-service:
    <<: *default-service
    build: src/pricing-service
    image: pricing-service:${BUILD_NUMBER}
    container_name: pricing-service 
    depends_on:
      - db
      - rabbitmq
    ports:
      - 8083:8080
    networks:
      - mynetwork      
    environment:
      MSSQL_CONNECTIONSTRING: *go-connection-string
      RABBITMQ_HOST: pricing-service 
      RABBITMQ_USER: userxxx
      RABBITMQ_PASSWORD: passxxx
      RABBITMQ_QUEUE: Trade_Data_Raw
      PROXY_PREFIX: pricing-service
      DT_CLUSTER_ID: easytrade-rabbitmq${STAGE}
      JOB_NAME: ${JOB_NAME}
      RELEASE_VERSION: ${BUILD_NUMBER}
      RELEASE_STAGE: ${STAGE}
      DT_TAGS: Environment=${STAGE} Service=pricing-service 
      DT_CUSTOM_PROP: ENVIRONMENT=${STAGE} JOB_NAME=${JOB_NAME} BUILD_NUMBER=${BUILD_NUMBER}

  broker-service:
    <<: *default-service
    build: src/broker-service
    image: broker-service:${BUILD_NUMBER}
    container_name: broker-service 
    ports:
      - 8084:80
    networks:
      - mynetwork      
    depends_on:
      - db
      - accountservice
      - pricing-service
      - feature-flag-service
    environment:
      ACCOUNTSERVICE_HOSTANDPORT: accountservice:8080
      PRICINGSERVICE_HOSTANDPORT: pricing-service:8080
      ENGINE_HOSTANDPORT: engine:8080
      <<: *feature-flag-service-env
      PROXY_PREFIX: broker-service
      MSSQL_CONNECTIONSTRING: *dotnet-connection-string
      DT_CLUSTER_ID: easytrade-broker-service-${STAGE} 
      JOB_NAME: ${JOB_NAME}
      RELEASE_VERSION: ${BUILD_NUMBER}
      RELEASE_STAGE: ${STAGE}
      DT_TAGS: Environment=${STAGE} Service=broker-service 
      DT_CUSTOM_PROP: ENVIRONMENT=${STAGE} JOB_NAME=${JOB_NAME} BUILD_NUMBER=${BUILD_NUMBER}

  rabbitmq:
    <<: *default-service
    build: src/rabbitmq
    image: rabbitmq:${BUILD_NUMBER}
    container_name: rabbitmq 
    ports:
      - 8082:15672
    networks:
      - mynetwork      
    environment:    
      DT_CLUSTER_ID: easytrade-rabbitmq${STAGE} 
      JOB_NAME: ${JOB_NAME}
      RELEASE_VERSION: ${BUILD_NUMBER}
      RELEASE_STAGE: ${STAGE}
      DT_TAGS: Environment=${STAGE} Service=rabbitmq 
      DT_CUSTOM_PROP: ENVIRONMENT=${STAGE} JOB_NAME=${JOB_NAME} BUILD_NUMBER=${BUILD_NUMBER}

  calculationservice:
    <<: *default-service
    build: src/calculationservice
    image: calcuationservice:${BUILD_NUMBER}
    container_name: calcuationservice 
    depends_on:
      - rabbitmq
    networks:
      - mynetwork      
    environment:    
      DT_CLUSTER_ID: easytrade-calculationservice${STAGE} 
      JOB_NAME: ${JOB_NAME}
      RELEASE_VERSION: ${BUILD_NUMBER}
      RELEASE_STAGE: ${STAGE}
      DT_TAGS: Environment=${STAGE} Service=calculationservice 
      DT_CUSTOM_PROP: ENVIRONMENT=${STAGE} JOB_NAME=${JOB_NAME} BUILD_NUMBER=${BUILD_NUMBER}

  frontend:
    <<: *default-service
    build:
      context: src/frontend
      dockerfile: Dockerfile.dev
    # depends_on:
    #   - broker-service
    #   - loginservice
    #   - pricing-service
    #   - accountservice
    #   - credit-card-order-service
    image: frontend:${BUILD_NUMBER}
    container_name: frontend 
    ports:
      - 8092:3000
    volumes:
      - /home/d1pacmworkshop/easytradeapp/src/frontend/src:/app/src:ro
            #- ./src/frontend/src:/app/src:ro
    networks:
      - mynetwork      
    environment:    
      DT_CLUSTER_ID: easytrade-frontend${STAGE}
      JOB_NAME: ${JOB_NAME}
      RELEASE_VERSION: ${BUILD_NUMBER}
      RELEASE_STAGE: ${STAGE}
      DT_TAGS: Environment=${STAGE} Service=frontend 
      DT_CUSTOM_PROP: ENVIRONMENT=${STAGE} JOB_NAME=${JOB_NAME} BUILD_NUMBER=${BUILD_NUMBER}

  loginservice:
    <<: *default-service
    build: src/loginservice/easyTradeLoginService
    image: loginservice:${BUILD_NUMBER}
    container_name: loginservice 
    environment:
      MSSQL_CONNECTIONSTRING: *dotnet-connection-string
      PROXY_PREFIX: loginservice
      DT_CLUSTER_ID: easytrade-loginservice${STAGE} 
      JOB_NAME: ${JOB_NAME}
      RELEASE_VERSION: ${BUILD_NUMBER}
      RELEASE_STAGE: ${STAGE}
      DT_TAGS: Environment=${STAGE} Service=loginservice 
      DT_CUSTOM_PROP: ENVIRONMENT=${STAGE} JOB_NAME=${JOB_NAME} BUILD_NUMBER=${BUILD_NUMBER}
    networks:
      - mynetwork      
    depends_on:
      - db
    ports:
      - 8086:80

  frontendreverseproxy:
    <<: *default-service
    build: src/frontendreverseproxy
    image: frontendreverseproxy:${BUILD_NUMBER}
    container_name: frontendreverseproxy 
    networks:
      - mynetwork      
    depends_on:
      - broker-service
      - frontend
      - loginservice
      - pricing-service
      - feature-flag-service
      - offerservice
      - accountservice
      - engine
      - credit-card-order-service
      - third-party-service
    ports:
      - 80:80
    environment:    
      DT_CLUSTER_ID: easytrade-frontendreverseproxy${STAGE}
      JOB_NAME: ${JOB_NAME}
      RELEASE_VERSION: ${BUILD_NUMBER}
      RELEASE_STAGE: ${STAGE}
      DT_TAGS: Environment=${STAGE} Service=frontendreverseproxy 
      DT_CUSTOM_PROP: ENVIRONMENT=${STAGE} JOB_NAME=${JOB_NAME} BUILD_NUMBER=${BUILD_NUMBER}

  offerservice:
    <<: *default-service
    build: src/offerservice
    image: offerservice:${BUILD_NUMBER}
    container_name: offerservice 
    depends_on:
      - loginservice
      - manager
      - feature-flag-service
    ports:
      - 8087:8080
    networks:
      - mynetwork      
    environment:
      <<: *feature-flag-service-env
      LOGIN_SERVICE_PORT: 80
      LOGIN_SERVICE_BASE_URL: loginservice
      MANAGER_BASE_URL: manager
      MANAGER_PORT: 80
      DT_CLUSTER_ID: easytrade-offerservice${STAGE}
      JOB_NAME: ${JOB_NAME}
      RELEASE_VERSION: ${BUILD_NUMBER}
      RELEASE_STAGE: ${STAGE}
      DT_TAGS: Environment=${STAGE} Service=loginservice 
      DT_CUSTOM_PROP: ENVIRONMENT=${STAGE} JOB_NAME=${JOB_NAME} BUILD_NUMBER=${BUILD_NUMBER}

  accountservice:
    <<: *default-service
    build: src/accountservice
    image: accountservice:${BUILD_NUMBER}
    container_name: accountservice 
    depends_on:
      - manager
    ports:
      - 8089:8080
    networks:
      - mynetwork      
    environment:
      MANAGER_HOSTANDPORT: manager:80
      PROXY_PREFIX: accountservice
      DT_CLUSTER_ID: easytrade-accountservice${STAGE} 
      JOB_NAME: ${JOB_NAME}
      RELEASE_VERSION: ${BUILD_NUMBER}
      RELEASE_STAGE: ${STAGE}
      DT_TAGS: Environment=${STAGE} Service=accountservice 
      DT_CUSTOM_PROP: ENVIRONMENT=${STAGE} JOB_NAME=${JOB_NAME} BUILD_NUMBER=${BUILD_NUMBER}

  engine:
    <<: *default-service
    build: src/engine
    image: engine:${BUILD_NUMBER}
    container_name: engine 
    depends_on:
      - broker-service
    ports:
      - 8090:8080
    networks:
      - mynetwork      
    environment:
      BROKER_HOSTANDPORT: broker-service:80
      PROXY_PREFIX: engine
      DT_CLUSTER_ID: easytrade-engine${STAGE} 
      JOB_NAME: ${JOB_NAME}
      RELEASE_VERSION: ${BUILD_NUMBER}
      RELEASE_STAGE: ${STAGE}
      DT_TAGS: Environment=${STAGE} Service=broker-service 
      DT_CUSTOM_PROP: ENVIRONMENT=${STAGE} JOB_NAME=${JOB_NAME} BUILD_NUMBER=${BUILD_NUMBER}

  credit-card-order-service:
    <<: *default-service
    build: src/credit-card-order-service
    image: credit-card-order-service:${BUILD_NUMBER}
    container_name: credit-card-order-service 
    depends_on:
      - db
      - third-party-service
    networks:
      - mynetwork      
    ports:
      - 8091:8080
    environment:
      PROXY_PREFIX: credit-card-order-service
      MSSQL_CONNECTIONSTRING: *java-connection-string
      THIRD_PARTY_SERVICE_HOSTANDPORT: third-party-service:8080
      <<: *feature-flag-service-env
      WORK_DELAY: 30
      WORK_RATE: 30
      DT_CLUSTER_ID: easytrade-credit-card-order-service-${STAGE} 
      JOB_NAME: ${JOB_NAME}
      RELEASE_VERSION: ${BUILD_NUMBER}
      RELEASE_STAGE: ${STAGE}
      DT_TAGS: Environment=${STAGE} Service=credit-card-order-service 
      DT_CUSTOM_PROP: ENVIRONMENT=${STAGE} JOB_NAME=${JOB_NAME} BUILD_NUMBER=${BUILD_NUMBER}

  third-party-service:
    <<: *default-service
    build: src/third-party-service
    image: third-party-service:${BUILD_NUMBER}
    container_name: third-party-service 
    ports:
      - 8093:8080
    environment:
      <<: *feature-flag-service-env
      PROXY_PREFIX: third-party-service
      CREDIT_CARD_ORDER_SERVICE_HOSTANDPORT: credit-card-order-service:8080
      COURIER_DELAY: 10
      COURIER_RATE: 10
      MANUFACTURE_DELAY: 10
      MANUFACTURE_RATE: 10
      DT_CLUSTER_ID: easytrade-third-party-service-${STAGE}
      JOB_NAME: ${JOB_NAME}
      RELEASE_VERSION: ${BUILD_NUMBER}
      RELEASE_STAGE: ${STAGE}
      DT_TAGS: Environment=${STAGE} Service=third-party-service
      DT_CUSTOM_PROP: ENVIRONMENT=${STAGE} JOB_NAME=${JOB_NAME} BUILD_NUMBER=${BUILD_NUMBER}
    networks:
      - mynetwork      

  feature-flag-service:
    <<: *default-service
    build: src/feature-flag-service
    image: feature-flag-service:${BUILD_NUMBER}
    container_name: feature-flag-service 
    ports:
      - 8094:8080
    environment:
      PROXY_PREFIX: feature-flag-service
      DT_CLUSTER_ID: easytrade-feature-flag-service-${STAGE}
      JOB_NAME: ${JOB_NAME}
      RELEASE_VERSION: ${BUILD_NUMBER}
      RELEASE_STAGE: ${STAGE}
      DT_TAGS: Environment=${STAGE} Service=feature-flag-service 
      DT_CUSTOM_PROP: ENVIRONMENT=${STAGE} JOB_NAME=${JOB_NAME} BUILD_NUMBER=${BUILD_NUMBER}
    networks:
      - mynetwork      

  aggregatorservice_1:
    <<: *default-aggregator-service
    build: src/aggregatorservice
    image: aggregatorservice_1:${BUILD_NUMBER}
    container_name: aggregatorservice_1 
    environment:
      <<: *default-aggregator-service-env
      PLATFORM: dynatestsieger.at
      STARTER_PACKAGE_PROBABILITY: 0.6
      LIGHT_PACKAGE_PROBABILITY: 0.3
      PRO_PACKAGE_PROBABILITY: 0.1
      DT_CLUSTER_ID: easytrade-aggregatorservice_1-${STAGE} 
      JOB_NAME: ${JOB_NAME}
      RELEASE_VERSION: ${BUILD_NUMBER}
      RELEASE_STAGE: ${STAGE}
      DT_TAGS: Environment=${STAGE} Service=aggregatorservice_1 
      DT_CUSTOM_PROP: ENVIRONMENT=${STAGE} JOB_NAME=${JOB_NAME} BUILD_NUMBER=${BUILD_NUMBER}
    networks:
      - mynetwork      

