FROM node:18.18.2-bullseye

LABEL ENV="DEV"

WORKDIR /app/

COPY ["*.json", "yarn.lock", "./"]

RUN yarn install --network-timeout 100000

COPY ["vite.config.ts", "index.html", "env.ts", ".env.*", "./"]

CMD ["yarn", "run", "dev", "--host", "-d"]

RUN yarn add vite @vitejs/plugin-react-swc @julr/vite-plugin-validate-env \
    && yarn cache clean \
    && echo '{ "type": "module" }' > package.json
