FROM node:18.18.2-bullseye

LABEL ENV="DEV"

WORKDIR /app/src

COPY ["*.json", "yarn.lock", "./"]

RUN yarn install --network-timeout 100000

COPY ["vite.config.ts", "index.html", "env.ts", ".env.*", "./"]

CMD ["yarn", "run", "dev", "--host", "-d"]

